# 
# Synthesis run script generated by Vivado
# 

set_param general.maxThreads 8
set_param xicom.use_bs_reader 1
set_param simulator.modelsimInstallPath C:/modeltech64_10.4/win64
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tftg256-3

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir E:/Users/Ykersatomi/Desktop/project_1/project_1.cache/wt [current_project]
set_property parent.project_path E:/Users/Ykersatomi/Desktop/project_1/project_1.xpr [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo e:/Users/Ykersatomi/Desktop/project_1/project_1.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog {
  E:/Users/Ykersatomi/Desktop/project_1/project_1.srcs/sources_1/new/timescale.vh
  E:/Users/Ykersatomi/Desktop/project_1/project_1.srcs/sources_1/new/i2cSlave_define.vh
  E:/Users/Ykersatomi/Desktop/project_1/project_1.srcs/sources_1/new/hardwarefpgadefine.vh
  E:/Users/Ykersatomi/Desktop/project_1/project_1.srcs/sources_1/new/phasefpgaregdef.vh
  E:/Users/Ykersatomi/Desktop/project_1/project_1.srcs/sources_1/new/controlfpgaregdef.vh
}
read_verilog -library xil_defaultlib {
  E:/Users/Ykersatomi/Desktop/project_1/project_1.srcs/sources_1/new/i2cMaster.v
  E:/Users/Ykersatomi/Desktop/project_1/project_1.srcs/sources_1/new/fan_ctrl.v
  E:/Users/Ykersatomi/Desktop/project_1/project_1.srcs/sources_1/new/i2c_read_loop.v
  E:/Users/Ykersatomi/Desktop/project_1/project_1.srcs/sources_1/new/serialInterface.v
  E:/Users/Ykersatomi/Desktop/project_1/project_1.srcs/sources_1/new/amp_ctrl.v
  E:/Users/Ykersatomi/Desktop/project_1/project_1.srcs/sources_1/new/dna.v
  E:/Users/Ykersatomi/Desktop/project_1/project_1.srcs/sources_1/new/fan_temp.v
  E:/Users/Ykersatomi/Desktop/project_1/project_1.srcs/sources_1/new/i2cSlave.v
  E:/Users/Ykersatomi/Desktop/project_1/project_1.srcs/sources_1/new/sync.v
  E:/Users/Ykersatomi/Desktop/project_1/project_1.srcs/sources_1/new/PHS_CRTL.v
}
read_ip -quiet e:/Users/Ykersatomi/Desktop/project_1/project_1.srcs/sources_1/ip/clk_gen/clk_gen.xci
set_property used_in_implementation false [get_files -all e:/Users/Ykersatomi/Desktop/project_1/project_1.srcs/sources_1/ip/clk_gen/clk_gen_board.xdc]
set_property used_in_implementation false [get_files -all e:/Users/Ykersatomi/Desktop/project_1/project_1.srcs/sources_1/ip/clk_gen/clk_gen.xdc]
set_property used_in_implementation false [get_files -all e:/Users/Ykersatomi/Desktop/project_1/project_1.srcs/sources_1/ip/clk_gen/clk_gen_ooc.xdc]
set_property is_locked true [get_files e:/Users/Ykersatomi/Desktop/project_1/project_1.srcs/sources_1/ip/clk_gen/clk_gen.xci]

foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc E:/Users/Ykersatomi/Desktop/project_1/project_1.srcs/constrs_1/new/PHS_CTRL.xdc
set_property used_in_implementation false [get_files E:/Users/Ykersatomi/Desktop/project_1/project_1.srcs/constrs_1/new/PHS_CTRL.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top PHS_CTRL -part xc7a100tftg256-3


write_checkpoint -force -noxdef PHS_CTRL.dcp

catch { report_utilization -file PHS_CTRL_utilization_synth.rpt -pb PHS_CTRL_utilization_synth.pb }
