# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a100tftg256-3

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/admin/Desktop/SDHW-PAU-FPGA-CTRL-I/CTRL.cache/wt [current_project]
set_property parent.project_path C:/Users/admin/Desktop/SDHW-PAU-FPGA-CTRL-I/CTRL.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/admin/Desktop/SDHW-PAU-FPGA-CTRL-I/CTRL.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog {
  C:/Users/admin/Desktop/SDHW-PAU-FPGA-CTRL-I/src/timescale.vh
  C:/Users/admin/Desktop/SDHW-PAU-FPGA-CTRL-I/src/simulation.vh
  C:/Users/admin/Desktop/SDHW-PAU-FPGA-CTRL-I/src/i2cSlave_define.vh
  C:/Users/admin/Desktop/SDHW-PAU-FPGA-CTRL-I/src/hardwarefpgadefine.vh
  C:/Users/admin/Desktop/SDHW-PAU-FPGA-CTRL-I/src/controlfpgaregdef.vh
}
read_verilog -library xil_defaultlib {
  C:/Users/admin/Desktop/SDHW-PAU-FPGA-CTRL-I/src/I2CMaster.v
  C:/Users/admin/Desktop/SDHW-PAU-FPGA-CTRL-I/src/amp_ctrl.v
  C:/Users/admin/Desktop/SDHW-PAU-FPGA-CTRL-I/CTRL.srcs/sources_1/new/current_value_delay.v
  C:/Users/admin/Desktop/SDHW-PAU-FPGA-CTRL-I/src/dna.v
  C:/Users/admin/Desktop/SDHW-PAU-FPGA-CTRL-I/src/fan_ctrl.v
  C:/Users/admin/Desktop/SDHW-PAU-FPGA-CTRL-I/src/fan_temp.v
  C:/Users/admin/Desktop/SDHW-PAU-FPGA-CTRL-I/src/i2cSlave.v
  C:/Users/admin/Desktop/SDHW-PAU-FPGA-CTRL-I/src/i2c_read_loop.v
  C:/Users/admin/Desktop/SDHW-PAU-FPGA-CTRL-I/src/serialInterface.v
  C:/Users/admin/Desktop/SDHW-PAU-FPGA-CTRL-I/src/sync.v
  C:/Users/admin/Desktop/SDHW-PAU-FPGA-CTRL-I/CTRL.srcs/sources_1/new/value_delay.v
  C:/Users/admin/Desktop/SDHW-PAU-FPGA-CTRL-I/src/CTRL_FPGA.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/admin/Desktop/SDHW-PAU-FPGA-CTRL-I/src/CTR_FPGA.xdc
set_property used_in_implementation false [get_files C:/Users/admin/Desktop/SDHW-PAU-FPGA-CTRL-I/src/CTR_FPGA.xdc]

set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top CTRL_FPGA -part xc7a100tftg256-3


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef CTRL_FPGA.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file CTRL_FPGA_utilization_synth.rpt -pb CTRL_FPGA_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
