# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/admin/Desktop/fifo_nsyn_test/fifo_nsyn_test.srcs/sources_1/ip/Bram/Bram.xci
# IP: The module: 'Bram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/admin/Desktop/fifo_nsyn_test/fifo_nsyn_test.srcs/sources_1/ip/Bram/Bram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Bram'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/admin/Desktop/fifo_nsyn_test/fifo_nsyn_test.srcs/sources_1/ip/Bram/Bram.xci
# IP: The module: 'Bram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/admin/Desktop/fifo_nsyn_test/fifo_nsyn_test.srcs/sources_1/ip/Bram/Bram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Bram'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
