# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: Core_ZYNQ.xdc

# Block Designs: bd/CPU/CPU.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CPU || ORIG_REF_NAME==CPU} -quiet] -quiet

# IP: bd/CPU/ip/CPU_AXI4_DEV_0_1/CPU_AXI4_DEV_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CPU_AXI4_DEV_0_1 || ORIG_REF_NAME==CPU_AXI4_DEV_0_1} -quiet] -quiet

# IP: bd/CPU/ip/CPU_AXI4_DEV_0_1/src/bram_2/bram.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bram || ORIG_REF_NAME==bram} -quiet] -quiet

# IP: bd/CPU/ip/CPU_processing_system7_0_0_1/CPU_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CPU_processing_system7_0_0 || ORIG_REF_NAME==CPU_processing_system7_0_0} -quiet] -quiet

# IP: bd/CPU/ip/CPU_ps7_0_axi_periph_0/CPU_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CPU_ps7_0_axi_periph_0 || ORIG_REF_NAME==CPU_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/CPU/ip/CPU_rst_ps7_0_100M_0_1/CPU_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CPU_rst_ps7_0_100M_0 || ORIG_REF_NAME==CPU_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/CPU/ip/CPU_auto_pc_0/CPU_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CPU_auto_pc_0 || ORIG_REF_NAME==CPU_auto_pc_0} -quiet] -quiet

# XDC: bd/CPU/ip/CPU_AXI4_DEV_0_1/src/bram_2/bram_ooc.xdc

# XDC: bd/CPU/ip/CPU_processing_system7_0_0_1/CPU_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==CPU_processing_system7_0_0 || ORIG_REF_NAME==CPU_processing_system7_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/CPU/ip/CPU_rst_ps7_0_100M_0_1/CPU_rst_ps7_0_100M_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==CPU_rst_ps7_0_100M_0 || ORIG_REF_NAME==CPU_rst_ps7_0_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/CPU/ip/CPU_rst_ps7_0_100M_0_1/CPU_rst_ps7_0_100M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==CPU_rst_ps7_0_100M_0 || ORIG_REF_NAME==CPU_rst_ps7_0_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/CPU/ip/CPU_auto_pc_0/CPU_auto_pc_0_ooc.xdc

# XDC: bd/CPU/CPU_ooc.xdc
