#LOC

#set_property PACKAGE_PIN K16 [get_ports PL_PUDC_B]
#set_property PACKAGE_PIN Y9 [get_ports PL_GCLK]
#set_property PACKAGE_PIN F16 [get_ports SFP_LOS]
#set_property PACKAGE_PIN C18 [get_ports SFP_RATESEL]
#set_property PACKAGE_PIN D16 [get_ports SFP_SCL]
#set_property PACKAGE_PIN G17 [get_ports SFP_SDA]
#set_property PACKAGE_PIN B19 [get_ports SFP_TXDISABLE]
#set_property PACKAGE_PIN A18 [get_ports SFP_TXFAULT]
#set_property PACKAGE_PIN AB4 [get_ports PFLH_SCL]
#set_property PACKAGE_PIN AA7 [get_ports PFLH_SDA]
#set_property PACKAGE_PIN AB15[get_ports {CTRL_IRQ[2]}]
#set_property PACKAGE_PIN V14 [get_ports {CTRL_IRQ[3]}]
#set_property PACKAGE_PIN B22 [get_ports {CTRL_IRQ[4]}]
#set_property PACKAGE_PIN F18 [get_ports {CTRL_IRQ[5]}]
#set_property PACKAGE_PIN A19 [get_ports {CTRL_IRQ[6]}]
#set_property PACKAGE_PIN D17 [get_ports {CTRL_IRQ[7]}]
#set_property PACKAGE_PIN U17 [get_ports {CTRL_PROG_B[2]}]
#set_property PACKAGE_PIN V15 [get_ports {CTRL_PROG_B[3]}]
#set_property PACKAGE_PIN G19 [get_ports {CTRL_PROG_B[4]}]
#set_property PACKAGE_PIN D20 [get_ports {CTRL_PROG_B[5]}]
#set_property PACKAGE_PIN B16 [get_ports {CTRL_PROG_B[6]}]
#set_property PACKAGE_PIN G16 [get_ports {CTRL_PROG_B[7]}]
#set_property PACKAGE_PIN AB14[get_ports {CTRL_SCL[2]}]
#set_property PACKAGE_PIN AA14[get_ports {CTRL_SCL[3]}]
#set_property PACKAGE_PIN F21 [get_ports {CTRL_SCL[4]}]
#set_property PACKAGE_PIN E18 [get_ports {CTRL_SCL[5]}]
#set_property PACKAGE_PIN A16 [get_ports {CTRL_SCL[6]}]
#set_property PACKAGE_PIN E16 [get_ports {CTRL_SCL[7]}]
#set_property PACKAGE_PIN V17 [get_ports {CTRL_SDA[2]}]
#set_property PACKAGE_PIN Y15 [get_ports {CTRL_SDA[3]}]
#set_property PACKAGE_PIN A22 [get_ports {CTRL_SDA[4]}]
#set_property PACKAGE_PIN E19 [get_ports {CTRL_SDA[5]}]
#set_property PACKAGE_PIN G15 [get_ports {CTRL_SDA[6]}]
#set_property PACKAGE_PIN C17 [get_ports {CTRL_SDA[7]}]
#set_property PACKAGE_PIN AB16[get_ports {PHA_IRQ[2]}]
#set_property PACKAGE_PIN C22 [get_ports {PHA_IRQ[4]}]
#set_property PACKAGE_PIN A21 [get_ports {PHA_IRQ[5]}]
#set_property PACKAGE_PIN C19 [get_ports {PHA_IRQ[6]}]
#set_property PACKAGE_PIN F17 [get_ports {PHA_IRQ[7]}]
#set_property PACKAGE_PIN U15 [get_ports {PHA_PROG_B[3]}]
#set_property PACKAGE_PIN F22 [get_ports {PHA_PROG_B[4]}]
#set_property PACKAGE_PIN E21 [get_ports {PHA_PROG_B[5]}]
#set_property PACKAGE_PIN D18 [get_ports {PHA_PROG_B[6]}]
#set_property PACKAGE_PIN E15 [get_ports {PHA_PROG_B[7]}]
#set_property PACKAGE_PIN AB17[get_ports {PHA_SCL[2]}]
#set_property PACKAGE_PIN F19 [get_ports {PHA_SCL[4]}]
#set_property PACKAGE_PIN D22 [get_ports {PHA_SCL[5]}]
#set_property PACKAGE_PIN E20 [get_ports {PHA_SCL[6]}]
#set_property PACKAGE_PIN C15 [get_ports {PHA_SCL[7]}]
#set_property PACKAGE_PIN W18 [get_ports {PHA_SDA[2]}]
#set_property PACKAGE_PIN Y14 [get_ports {PHA_SDA[3]}]
#set_property PACKAGE_PIN D21 [get_ports {PHA_SDA[4]}]
#set_property PACKAGE_PIN B21 [get_ports {PHA_SDA[5]}]
#set_property PACKAGE_PIN C20 [get_ports {PHA_SDA[6]}]
#set_property PACKAGE_PIN B20 [get_ports {PHA_SDA[7]}]
#set_property PACKAGE_PIN AA4 [get_ports {PRESENT[2]}]
#set_property PACKAGE_PIN W6  [get_ports {PRESENT[4]}]
#set_property PACKAGE_PIN V5  [get_ports {PRESENT[5]}]
#set_property PACKAGE_PIN W5  [get_ports {PRESENT[6]}]
#set_property PACKAGE_PIN V4  [get_ports {PRESENT[7]}]
#set_property PACKAGE_PIN P20 [get_ports {USM_DRIVE_A_N[4]}]
#set_property PACKAGE_PIN M19 [get_ports {USM_DRIVE_A_P[4]}]
#set_property PACKAGE_PIN AB10[get_ports {USM_DRIVE_B_N[4]}]
#set_property PACKAGE_PIN AA11[get_ports {USM_DRIVE_B_P[4]}]
#set_property PACKAGE_PIN K18 [get_ports {USM_OUT_A[4]}]
#set_property PACKAGE_PIN G22 [get_ports {USM_OUT_B[4]}]
#set_property PACKAGE_PIN J20 [get_ports {USM_OUT_Z[4]}]
#set_property PACKAGE_PIN V12 [get_ports {USM_POWERCTRL[4]}]
#set_property PACKAGE_PIN L17 [get_ports {USM_ALARM_A[4]}]
#set_property PACKAGE_PIN J17 [get_ports {USM_ALARM_B[4]}]
#set_property PACKAGE_PIN J15 [get_ports {USM_ALARM_D[4]}]
#set_property PACKAGE_PIN G21 [get_ports {USM_ALARM_Z[4]}]
#set_property PACKAGE_PIN Y13 [get_ports {PWR_AC_OK[2]}]
#set_property PACKAGE_PIN U9  [get_ports {PWR_AC_OK[3]}]
#set_property PACKAGE_PIN V13 [get_ports {PWR_DC_OK[2]}]
#set_property PACKAGE_PIN U10 [get_ports {PWR_DC_OK[3]}]
#set_property PACKAGE_PIN AA12[get_ports {PWR_FAULT[2]}]
#set_property PACKAGE_PIN U11 [get_ports {PWR_FAULT[3]}]
#set_property PACKAGE_PIN U12 [get_ports {PWR_INHIBIT[2]}]
#set_property PACKAGE_PIN AB12[get_ports {PWR_INHIBIT[3]}]
#set_property PACKAGE_PIN V19 [get_ports {PWR_SCL[2]}]
#set_property PACKAGE_PIN AA13[get_ports {PWR_SCL[3]}]
#set_property PACKAGE_PIN V20 [get_ports {PWR_SDA[2]}]
#set_property PACKAGE_PIN W13 [get_ports {PWR_SDA[3]}]


set_property PACKAGE_PIN U16 [get_ports XDCR_PRESENT]
set_property PACKAGE_PIN W15 [get_ports XDCR_SCL]
set_property PACKAGE_PIN Y14 [get_ports XDCR_SDA]

set_property PACKAGE_PIN B17  [get_ports CLOCK_SCL]
set_property PACKAGE_PIN A17  [get_ports CLOCK_SDA]
set_property PACKAGE_PIN K20  [get_ports TRIGGER]
set_property PACKAGE_PIN AB1  [get_ports RTC_SCL]
set_property PACKAGE_PIN Y5   [get_ports RTC_SDA]
set_property PACKAGE_PIN T18  [get_ports {PL_SWITCH[0]}]
set_property PACKAGE_PIN P16  [get_ports {PL_SWITCH[1]}]
set_property PACKAGE_PIN N15  [get_ports {PL_SWITCH[2]}]
set_property PACKAGE_PIN R18  [get_ports {PL_SWITCH[3]}]
set_property PACKAGE_PIN R16  [get_ports {PL_SWITCH[4]}]
set_property PACKAGE_PIN AB7  [get_ports {PL_LED[0]}]
set_property PACKAGE_PIN V8   [get_ports {PL_LED[1]}]
set_property PACKAGE_PIN V7   [get_ports {PL_LED[2]}]
set_property PACKAGE_PIN D15  [get_ports {PL_LED[3]}]
set_property PACKAGE_PIN AA6  [get_ports {PL_UNUSED[0]}]
set_property PACKAGE_PIN Y8   [get_ports {PL_UNUSED[1]}]
set_property PACKAGE_PIN B15  [get_ports {PL_UNUSED[2]}]
set_property PACKAGE_PIN L16  [get_ports {PL_UNUSED[3]}]
set_property PACKAGE_PIN T19  [get_ports {EMERMEA[0]}]
set_property PACKAGE_PIN U19  [get_ports {EMERMEA[1]}]
set_property PACKAGE_PIN AB2  [get_ports {USM_LIMIT[0]}]
set_property PACKAGE_PIN AB5  [get_ports {USM_LIMIT[1]}]
set_property PACKAGE_PIN Y6   [get_ports {USM_LIMIT[2]}]
set_property PACKAGE_PIN Y4   [get_ports {USM_LIMIT[3]}]
set_property PACKAGE_PIN AA19 [get_ports {CTRL_IRQ[0]}]
set_property PACKAGE_PIN Y16  [get_ports {CTRL_IRQ[1]}]
set_property PACKAGE_PIN Y20  [get_ports {CTRL_PROG_B[0]}]
set_property PACKAGE_PIN W16  [get_ports {CTRL_PROG_B[1]}]
set_property PACKAGE_PIN AA21 [get_ports {CTRL_SCL[0]}]
set_property PACKAGE_PIN AA16 [get_ports {CTRL_SCL[1]}]
set_property PACKAGE_PIN AA22 [get_ports {CTRL_SDA[0]}]
set_property PACKAGE_PIN W17  [get_ports {CTRL_SDA[1]}]
set_property PACKAGE_PIN AB20 [get_ports {PHA_IRQ[0]}]
set_property PACKAGE_PIN AA17 [get_ports {PHA_IRQ[1]}]
set_property PACKAGE_PIN AB22 [get_ports {PHA_PROG_B[0]}]
set_property PACKAGE_PIN AB19 [get_ports {PHA_PROG_B[1]}]
set_property PACKAGE_PIN AB21 [get_ports {PHA_SCL[0]}]
set_property PACKAGE_PIN Y19  [get_ports {PHA_SCL[1]}]
set_property PACKAGE_PIN Y21  [get_ports {PHA_SDA[0]}]
set_property PACKAGE_PIN Y18  [get_ports {PHA_SDA[1]}]
set_property PACKAGE_PIN G20  [get_ports {PRESENT[0]}]
set_property PACKAGE_PIN H18  [get_ports {PRESENT[1]}]
set_property PACKAGE_PIN L19  [get_ports USM_PWR_SW]
set_property PACKAGE_PIN W11  [get_ports {USM_DRIVE_A_N[0]}]
set_property PACKAGE_PIN M21  [get_ports {USM_DRIVE_A_N[1]}]
set_property PACKAGE_PIN AA8  [get_ports {USM_DRIVE_A_N[2]}]
set_property PACKAGE_PIN Y11  [get_ports {USM_DRIVE_A_N[3]}]
set_property PACKAGE_PIN W7   [get_ports {USM_DRIVE_A_P[0]}]
set_property PACKAGE_PIN AB6  [get_ports {USM_DRIVE_A_P[1]}]
set_property PACKAGE_PIN P22  [get_ports {USM_DRIVE_A_P[2]}]
set_property PACKAGE_PIN AB11 [get_ports {USM_DRIVE_A_P[3]}]
set_property PACKAGE_PIN V10  [get_ports {USM_DRIVE_B_N[0]}]
set_property PACKAGE_PIN R20  [get_ports {USM_DRIVE_B_N[1]}]
set_property PACKAGE_PIN V9   [get_ports {USM_DRIVE_B_N[2]}]
set_property PACKAGE_PIN Y10  [get_ports {USM_DRIVE_B_N[3]}]
set_property PACKAGE_PIN AA9  [get_ports {USM_DRIVE_B_P[0]}]
set_property PACKAGE_PIN N22  [get_ports {USM_DRIVE_B_P[1]}]
set_property PACKAGE_PIN R21  [get_ports {USM_DRIVE_B_P[2]}]
set_property PACKAGE_PIN AB9  [get_ports {USM_DRIVE_B_P[3]}]
set_property PACKAGE_PIN N17  [get_ports {USM_OUT_A[0]}]
set_property PACKAGE_PIN K15  [get_ports {USM_OUT_A[1]}]
set_property PACKAGE_PIN H22  [get_ports {USM_OUT_A[2]}]
set_property PACKAGE_PIN P17  [get_ports {USM_OUT_A[3]}]
set_property PACKAGE_PIN T17  [get_ports {USM_OUT_B[0]}]
set_property PACKAGE_PIN H20  [get_ports {USM_OUT_B[1]}]
set_property PACKAGE_PIN M22  [get_ports {USM_OUT_B[2]}]
set_property PACKAGE_PIN M20  [get_ports {USM_OUT_B[3]}]
set_property PACKAGE_PIN L18  [get_ports {USM_OUT_Z[0]}]
set_property PACKAGE_PIN K21  [get_ports {USM_OUT_Z[1]}]
set_property PACKAGE_PIN J21  [get_ports {USM_OUT_Z[2]}]
set_property PACKAGE_PIN K19  [get_ports {USM_OUT_Z[3]}]
set_property PACKAGE_PIN W8   [get_ports {USM_POWERCTRL[0]}]
set_property PACKAGE_PIN L21  [get_ports {USM_POWERCTRL[1]}]
set_property PACKAGE_PIN W10  [get_ports {USM_POWERCTRL[2]}]
set_property PACKAGE_PIN W12  [get_ports {USM_POWERCTRL[3]}]
set_property PACKAGE_PIN P15  [get_ports {USM_ALARM_A[0]}]
set_property PACKAGE_PIN J18  [get_ports {USM_ALARM_A[1]}]
set_property PACKAGE_PIN N19  [get_ports {USM_ALARM_A[2]}]
set_property PACKAGE_PIN N18  [get_ports {USM_ALARM_A[3]}]
set_property PACKAGE_PIN N20  [get_ports {USM_ALARM_B[0]}]
set_property PACKAGE_PIN J22  [get_ports {USM_ALARM_B[1]}]
set_property PACKAGE_PIN H19  [get_ports {USM_ALARM_B[2]}]
set_property PACKAGE_PIN P21  [get_ports {USM_ALARM_B[3]}]
set_property PACKAGE_PIN M17  [get_ports {USM_ALARM_D[0]}]
set_property PACKAGE_PIN J16  [get_ports {USM_ALARM_D[1]}]
set_property PACKAGE_PIN T16  [get_ports {USM_ALARM_D[2]}]
set_property PACKAGE_PIN M16  [get_ports {USM_ALARM_D[3]}]
set_property PACKAGE_PIN P18  [get_ports {USM_ALARM_Z[0]}]
set_property PACKAGE_PIN H17  [get_ports {USM_ALARM_Z[1]}]
set_property PACKAGE_PIN L22  [get_ports {USM_ALARM_Z[2]}]
set_property PACKAGE_PIN M15  [get_ports {USM_ALARM_Z[3]}]
set_property PACKAGE_PIN U14  [get_ports {PWR_AC_OK[0]}]
set_property PACKAGE_PIN W20  [get_ports {PWR_AC_OK[1]}]
set_property PACKAGE_PIN R19  [get_ports {PWR_DC_OK[0]}]
set_property PACKAGE_PIN V22  [get_ports {PWR_DC_OK[1]}]
set_property PACKAGE_PIN T21  [get_ports {PWR_FAULT[0]}]
set_property PACKAGE_PIN U20  [get_ports {PWR_FAULT[1]}]
set_property PACKAGE_PIN T22  [get_ports {PWR_INHIBIT[0]}]
set_property PACKAGE_PIN V18  [get_ports {PWR_INHIBIT[1]}]
set_property PACKAGE_PIN U22  [get_ports {PWR_SCL[0]}]
set_property PACKAGE_PIN W21  [get_ports {PWR_SCL[1]}]
set_property PACKAGE_PIN U21  [get_ports {PWR_SDA[0]}]
set_property PACKAGE_PIN W22  [get_ports {PWR_SDA[1]}]


#Level
set_property IOSTANDARD LVCMOS33 [get_ports *]

set_property PULLUP true [get_ports *_SCL]
set_property PULLUP true [get_ports *_SDA]
set_property PULLUP true [get_ports USM_LIMIT[*]]
set_property PULLUP true [get_ports USM_PWR_SW]
set_property PULLDOWN true [get_ports TRIGGER]
set_property PULLDOWN true [get_ports {CTRL_IRQ[*]}]
set_property PULLDOWN true [get_ports {PHA_IRQ[*]}]



